(in-package :cl-jquants-api.test)

(defclass mock-http-handler (cl-jquants-api::http-handler)
  ())

(defclass pagination-mock-http-handler (cl-jquants-api::http-handler)
  ((call-count :initform 0 :accessor call-count)
   (last-endpoint :initform nil :accessor last-endpoint)))

(defun %get-json-file-path (filename)
  (merge-pathnames filename (asdf:system-relative-pathname "cl-jquants-api" "t/data/")))

(defun %mock-http-response-from-json (filename)
  (when-let (json (read-file-into-string (%get-json-file-path filename)))
    (yason:parse json)))

(defmethod send-request ((obj mock-http-handler) endpoint method
                         &key (content nil) (stream *standard-output*) (timeout 20))
  (declare (ignore method content stream timeout))
  (flet ((string-match (text endpoint)
           (cl-ppcre:scan text endpoint)))
    (cond ((string-match "equities/master" endpoint)
           (%mock-http-response-from-json "ListedIssueInformation.json"))
          ((string-match "equities/bars/daily/am" endpoint)
           (%mock-http-response-from-json "MorningSessionStockPrices.json"))
          ((string-match "equities/bars/daily" endpoint)
           (%mock-http-response-from-json "StockPrices.json"))
          ((string-match "equities/investor-types" endpoint)
           (%mock-http-response-from-json "TradingByTypeOfInvestors.json"))
          ((string-match "equities/earnings-calendar" endpoint)
           (%mock-http-response-from-json "EarningsCalendar.json"))
          ((string-match "markets/margin-interest" endpoint)
           (%mock-http-response-from-json "MarginTradingOutstandings.json"))
          ((string-match "markets/short-ratio" endpoint)
           (%mock-http-response-from-json "ShortSaleValueAndRatioBySector.json"))
          ((string-match "markets/breakdown" endpoint)
           (%mock-http-response-from-json "BreakdownTradingData.json"))
          ((string-match "markets/calendar" endpoint)
           (%mock-http-response-from-json "TradingCalendar.json"))
          ((string-match "indices/bars/daily/topix" endpoint)
           (%mock-http-response-from-json "TopixPrices.json"))
          ((string-match "indices/bars/daily" endpoint)
           (%mock-http-response-from-json "IndicesPrices.json"))
          ((string-match "fins/summary" endpoint)
           (%mock-http-response-from-json "FinancialData.json"))
          ((string-match "fins/details" endpoint)
           (%mock-http-response-from-json "FinancialStatementData.json"))
          ((string-match "fins/dividend" endpoint)
           (%mock-http-response-from-json "CashDividendData.json"))
          ((string-match "derivatives/bars/daily/options/225" endpoint)
           (%mock-http-response-from-json "IndexOptionPrices.json"))
          ((string-match "derivatives/bars/daily/futures" endpoint)
           (%mock-http-response-from-json "FuturesData.json"))
          ((string-match "derivatives/bars/daily/options" endpoint)
           (%mock-http-response-from-json "OptionsData.json")))))

(defmethod send-request ((obj pagination-mock-http-handler) endpoint method
                         &key (content nil) (stream *standard-output*) (timeout 20))
  (declare (ignore method content stream timeout))
  (setf (last-endpoint obj) endpoint)
  (let ((page (incf (call-count obj))))
    (cond ((= page 1) (%mock-http-response-from-json "TopixPricesPage1.json"))
          (t          (%mock-http-response-from-json "TopixPricesPage2.json")))))
