(in-package :cl-jquants-api)

(defvar *locale* :en
  "")

(defparameter +end-point-base+ "https://api.jquants.com/v1")

(defparameter +token/auth-user+                "token/auth_user")
(defparameter +token/auth-refresh+             "token/auth_refresh")
(defparameter +listed/info+                    "listed/info")
(defparameter +prices/daily-quotes+            "prices/daily_quotes")
(defparameter +prices/prices-am+               "prices/prices_am")
(defparameter +markets/trades_spec+            "markets/trades_spec")
(defparameter +markets/weekly-margin-interest+ "markets/weekly_margin_interest")
(defparameter +markets/short-selling+          "markets/short_selling")
(defparameter +markets/breakdown+              "markets/breakdown")
(defparameter +markets/trading-calendar+       "markets/trading_calendar")
(defparameter +indices+                        "indices")
(defparameter +indices/topix+                  "indices/topix")
(defparameter +fins/statements+                "fins/statements")
(defparameter +fins/fs-details+                "fins/fs_details")
(defparameter +fins/dividend+                  "fins/dividend")
(defparameter +fins/announcement+              "fins/announcement")
(defparameter +option/index-option+            "option/index_option")
(defparameter +derivatives/futures+            "derivatives/futures")
(defparameter +derivatives/options+            "derivatives/options")

(defparameter +market-segment-code-and-name+
  '((:0101 . "1st Section")
    (:0102 . "2nd Section")
    (:0104 . "Mothers")
    (:0105 . "TOKYO PRO MARKET")
    (:0106 . "JASDAQ Standard")
    (:0107 . "JASDAQ Growth")
    (:0109 . "Others")
    (:0111 . "Prime")
    (:0112 . "Standard")
    (:0113 . "Growth"))
  "
 https://jpx.gitbook.io/j-quants-en/api-reference/listed_info/marketcode")

(defparameter +sector17-code-and-name+
  '((:1  . "FOODS")
    (:2  . "ENERGY RESOURCES")
    (:3  . "CONSTRUCTION & MATERIALS")
    (:4  . "RAW MATERIALS & CHEMICALS")
    (:5  . "PHARMACEUTICAL")
    (:6  . "AUTOMOBILES & TRANSPORTATION EQUIPMENT")
    (:7  . "STEEL & NONFERROUS METALS")
    (:8  . "MACHINERY")
    (:9  . "ELECTRIC APPLIANCES & PRECISION INSTRUMENTS")
    (:10 . "IT & SERVICES, OTHERS")
    (:11 . "ELECTRIC POWER & GAS")
    (:12 . "TRANSPORTATION & LOGISTICS")
    (:13 . "COMMERCIAL & WHOLESALE TRADE")
    (:14 . "RETAIL TRADE")
    (:15 . "BANKS")
    (:16 . "FINANCIALS (EX BANKS)")
    (:17 . "REAL ESTATE")
    (:99 . "OTHER"))
  "
https://jpx.gitbook.io/j-quants-en/api-reference/listed_info/sector17code")

(defparameter +sector33-code-and-name+
  '((:0050 . "Fishery, Agriculture & Forestry")
    (:1050 . "Mining")
    (:2050 . "Construction")
    (:3050 . "Foods")
    (:3100 . "Textiles & Apparels")
    (:3150 . "Pulp & Paper")
    (:3200 . "Chemicals")
    (:3250 . "Pharmaceutical")
    (:3300 . "Oil & Coal Products")
    (:3350 . "Rubber Products")
    (:3400 . "Glass & Ceramics Products")
    (:3450 . "Iron & Steel")
    (:3500 . "Nonferrous Metals")
    (:3550 . "Metal Products")
    (:3600 . "Machinery")
    (:3650 . "Electric Appliances")
    (:3700 . "Transportation Equipment")
    (:3750 . "Precision Instruments")
    (:3800 . "Other Products")
    (:4050 . "Electric Power & Gas")
    (:5050 . "Land Transportation")
    (:5100 . "Marine Transportation")
    (:5150 . "Air Transportation")
    (:5200 . "Warehousing & Harbor Transportation Services")
    (:5250 . "Information & Communication")
    (:6050 . "Wholesale Trade")
    (:6100 . "Retail Trade")
    (:7050 . "Banks")
    (:7100 . "Securities & Commodity Futures")
    (:7150 . "Insurance")
    (:7200 . "Other Financing Business")
    (:8050 . "Real Estate")
    (:9050 . "Services")
    (:9999 . "Other"))
"
https://jpx.gitbook.io/j-quants-en/api-reference/listed_info/sector33code")

(defparameter +index-code-name+
  '((:0000 . "TOPIX")
    (:0001 . "Second Section Stock Price Index")
    (:0028 . "TOPIX Core 30")
    (:0029 . "TOPIX Large 70")
    (:002A . "TOPIX 100")
    (:002B . "TOPIX Mid 400")
    (:002C . "TOPIX 500")
    (:002D . "TOPIX Small")
    (:002E . "TOPIX 1000")
    (:002F . "TOPIX Small 500")
    (:0040 . "Fishery, Agriculture & Forestry")
    (:0041 . "Mining")
    (:0042 . "Construction")
    (:0043 . "Foods")
    (:0044 . "Textiles & Apparels")
    (:0045 . "Pulp & Paper")
    (:0046 . "Chemicals")
    (:0047 . "Pharmaceutical")
    (:0048 . "Oil & Coal Products")
    (:0049 . "Rubber Products")
    (:004A . "Glass & Ceramics Products")
    (:004B . "Iron & Steel")
    (:004C . "Nonferrous Metals")
    (:004D . "Metal Products")
    (:004E . "Machinery")
    (:004F . "Electronic Appliances")
    (:0050 . "Transportation Equipment")
    (:0051 . "Precision Instruments")
    (:0052 . "Other Products")
    (:0053 . "Electric Power & Gas")
    (:0054 . "Land Transportation")
    (:0055 . "Marine Transportation")
    (:0056 . "Air Transportation")
    (:0057 . "Warehousing and Harbor Transportation Service")
    (:0058 . "Information & Communication")
    (:0059 . "Wholesale Trade")
    (:005A . "Retail Trade")
    (:005B . "Banks")
    (:005C . "Securities & Commodity Futures")
    (:005D . "Insurance")
    (:005E . "Other Financing Business")
    (:005F . "Real Estate")
    (:0060 . "Services")
    (:0070 . "Tokyo Stock Exchange Growth Market 250 Index")
    (:0075 . "REIT")
    (:0080 . "TOPIX-17 FOODS")
    (:0081 . "TOPIX-17 ENERGY RESOURCES")
    (:0082 . "TOPIX-17 CONSTRUCTION & MATERIALS")
    (:0083 . "TOPIX-17 RAW MATERIALS & CHEMICALS")
    (:0084 . "TOPIX-17 PHARMACEUTICAL")
    (:0085 . "TOPIX-17 AUTOMOBILES & TRANSPORTATION EQUIPMENT")
    (:0086 . "TOPIX-17 STEEL & NONFERROUS METALS")
    (:0087 . "TOPIX-17 MACHINERY")
    (:0088 . "TOPIX-17 ELECTRIC APPLIANCES & PRECISION INSTRUMENTS")
    (:0089 . "TOPIX-17 IT & SERVICES, OTHERS")
    (:008A . "TOPIX-17 ELECTRIC POWER & GAS")
    (:008B . "TOPIX-17 TRANSPORTATION & LOGISTICS")
    (:008C . "TOPIX-17 COMMERCIAL & WHOLESALE TRADE")
    (:008D . "TOPIX-17 RETAIL TRADE")
    (:008E . "TOPIX-17 BANKS")
    (:008F . "TOPIX-17 FINANCIALS(EX BANKS)")
    (:0090 . "TOPIX-17 REAL ESTATE")
    (:0091 . "JASDAQ INDEX")
    (:0500 . "Tokyo Stock Exchange Prime Market Index")
    (:0501 . "Tokyo Stock Exchange Standard Market Index")
    (:0502 . "Tokyo Stock Exchange Growth Market Index")
    (:0503 . "JPX Prime 150 Index")
    (:8100 . "TOPIX Value")
    (:812C . "TOPIX 500 Value")
    (:812D . "TOPIX Small Value")
    (:8200 . "TOPIX Growth")
    (:822C . "TOPIX 500 Growth")
    (:822D . "TOPIX Small Growth")
    (:8501 . "Tokyo Stock Exchange REIT Office Index")
    (:8502 . "Tokyo Stock Exchange REIT Residential Index")
    (:8503 . "Tokyo Stock Exchange REIT Retail & Logistics, Others Index"))
"
https://jpx.gitbook.io/j-quants-en/api-reference/indices/indices-codes")

(defparameter +margin-code+
  '((1 . "Margin issues")
    (2 . "Loan issues")
    (3 . "Other issues (non-loan, non-margin)")))

(defparameter +holiday-division+
  '((0 . "Non-business day")
    (1 . "Business day")
    (2 . "Day of TSE Half-Day Trading Sessions")
    (3 . "Non-business days (with holiday trading)")))

(defparameter +cash-dividend-status-code+
  '((1 . "New")
    (2 . "Revised")
    (3 . "Delete")))

(defparameter +cash-dividend-interim-final-code+
  '((1 . "Interim")
    (2 . "Final")))

(defparameter +cash-dividend-forecast-result-code+
  '((1 . "Interim")
    (2 . "Final")))

(defparameter +cash-dividend-commemorative-special-code+
  '((0 . "Normal")
    (1 . "Commemorative")
    (2 . "Special")
    (3 . "Both")))
