(in-package :cl-jquants-api)

(defclass financial-statement-detail-data (jquants-object)
  ((goodwill-ifrs :accessor goodwill-ifrs-of :initform 0.0)
   (retained-earnings-ifrs :accessor retained-earnings-ifrs-of :initform 0.0)
   (operating-profit-loss-ifrs :accessor operating-profit-loss-ifrs-of :initform 0.0)
   (previous-fiscal-year-end-date-dei :accessor previous-fiscal-year-end-date-dei-of :initform nil)
   (basic-earnings-loss-per-share-ifrs :accessor basic-earnings-loss-per-share-ifrs-of :initform 0.0)
   (document-type-dei :accessor document-type-dei-of :initform nil)
   (current-period-end-date-dei :accessor current-period-end-date-dei-of :initform nil)
   (revenue-2-ifrs :accessor revenue-2-ifrs-of :initform 0.0)
   (industry-code-when-consolidated-financial-statements-are-prepared-in-accordance-with-industry-specific-regulations-dei
    :accessor industry-code-when-consolidated-financial-statements-are-prepared-in-accordance-with-industry-specific-regulations-dei-of :initform nil)
   (profit-loss-attributable-to-owners-of-parent-ifrs :accessor profit-loss-attributable-to-owners-of-parent-ifrs-of :initform 0.0)
   (other-current-liabilities-cl-ifrs :accessor other-current-liabilities-cl-ifrs-of :initform 0.0)
   (share-of-profit-loss-of-investments-accounted-for-using-equity-method-ifrs
    :accessor share-of-profit-loss-of-investments-accounted-for-using-equity-method-ifrs-of :initform 0.0)
   (current-liabilities-ifrs :accessor current-liabilities-ifrs-of :initform 0.0)
   (equity-attributable-to-owners-of-parent-ifrs :accessor equity-attributable-to-owners-of-parent-ifrs-of :initform 0.0)
   (whether-consolidated-financial-statements-are-prepared-dei
    :accessor whether-consolidated-financial-statements-are-prepared-dei-of :initform nil)
   (non-current-liabilities-ifrs :accessor non-current-liabilities-ifrs-of :initform 0.0)
   (other-expenses-ifrs :accessor other-expenses-ifrs-of :initform 0.0)
   (income-taxes-payable-cl-ifrs :accessor income-taxes-payable-cl-ifrs-of :initform 0.0)
   (filer-name-in-english-dei :accessor filer-name-in-english-dei-of :initform nil)
   (non-controlling-interests-ifrs :accessor non-controlling-interests-ifrs-of :initform 0.0)
   (capital-surplus-ifrs :accessor capital-surplus-ifrs-of :initform 0.0)
   (finance-costs-ifrs :accessor finance-costs-ifrs-of :initform 0.0)
   (other-current-assets-ca-ifrs :accessor other-current-assets-ca-ifrs-of :initform 0.0)
   (property-plant-and-equipment-ifrs :accessor property-plant-and-equipment-ifrs-of :initform 0.0)
   (deferred-tax-liabilities-ifrs :accessor deferred-tax-liabilities-ifrs-of :initform 0.0)
   (other-components-of-equity-ifrs :accessor other-components-of-equity-ifrs-of :initform 0.0)
   (current-fiscal-year-start-date-dei :accessor current-fiscal-year-start-date-dei-of :initform nil)
   (type-of-current-period-dei :accessor type-of-current-period-dei-of :initform nil)
   (cash-and-cash-equivalents-ifrs :accessor cash-and-cash-equivalents-ifrs-of :initform 0.0)
   (share-capital-ifrs :accessor share-capital-ifrs-of :initform 0.0)
   (retirement-benefit-asset-nca-ifrs :accessor retirement-benefit-asset-nca-ifrs-of :initform 0.0)
   (number-of-submission-dei :accessor number-of-submission-dei-of :initform 0.0)
   (trade-and-other-receivables-ca-ifrs :accessor trade-and-other-receivables-ca-ifrs-of :initform 0.0)
   (liabilities-and-equity-ifrs :accessor liabilities-and-equity-ifrs-of :initform 0.0)
   (edinet-code-dei :accessor edinet-code-dei-of :initform nil)
   (equity-ifrs :accessor equity-ifrs-of :initform 0.0)
   (security-code-dei :accessor security-code-dei-of :initform nil)
   (other-financial-assets-ca-ifrs :accessor other-financial-assets-ca-ifrs-of :initform 0.0)
   (other-financial-assets-nca-ifrs :accessor other-financial-assets-nca-ifrs-of :initform 0.0)
   (income-taxes-receivable-ca-ifrs :accessor income-taxes-receivable-ca-ifrs-of :initform 0.0)
   (investments-accounted-for-using-equity-method-ifrs :accessor investments-accounted-for-using-equity-method-ifrs-of :initform 0.0)
   (other-non-current-assets-nca-ifrs :accessor other-non-current-assets-nca-ifrs-of :initform 0.0)
   (previous-fiscal-year-start-date-dei :accessor previous-fiscal-year-start-date-dei-of :initform nil)
   (filer-name-in-japanese-dei :accessor filer-name-in-japanese-dei-of :initform nil)
   (deferred-tax-assets-ifrs :accessor deferred-tax-assets-ifrs-of :initform 0.0)
   (trade-and-other-payables-cl-ifrs :accessor trade-and-other-payables-cl-ifrs-of :initform 0.0)
   (bonds-and-borrowings-cl-ifrs :accessor bonds-and-borrowings-cl-ifrs-of :initform 0.0)
   (current-fiscal-year-end-date-dei :accessor current-fiscal-year-end-date-dei-of :initform nil)
   (xbrl-amendment-flag-dei :accessor xbrl-amendment-flag-dei-of :initform nil)
   (non-current-assets-ifrs :accessor non-current-assets-ifrs-of :initform 0.0)
   (retirement-benefit-liability-ncl-ifrs :accessor retirement-benefit-liability-ncl-ifrs-of :initform 0.0)
   (amendment-flag-dei :accessor amendment-flag-dei-of :initform nil)
   (assets-ifrs :accessor assets-ifrs-of :initform 0.0)
   (income-tax-expense-ifrs :accessor income-tax-expense-ifrs-of :initform 0.0)
   (report-amendment-flag-dei :accessor report-amendment-flag-dei-of :initform nil)
   (profit-loss-ifrs :accessor profit-loss-ifrs-of :initform 0.0)
   (operating-expenses-ifrs :accessor operating-expenses-ifrs-of :initform 0.0)
   (intangible-assets-ifrs :accessor intangible-assets-ifrs-of :initform 0.0)
   (profit-loss-before-tax-from-continuing-operations-ifrs :accessor profit-loss-before-tax-from-continuing-operations-ifrs-of :initform 0.0)
   (liabilities-ifrs :accessor liabilities-ifrs-of :initform 0.0)
   (accounting-standards-dei :accessor accounting-standards-dei-of :initform 0.0)
   (bonds-and-borrowings-ncl-ifrs :accessor bonds-and-borrowings-ncl-ifrs-of :initform 0.0)
   (finance-income-ifrs :accessor finance-income-ifrs-of :initform 0.0)
   (profit-loss-attributable-to-non-controlling-interests-ifrs :accessor profit-loss-attributable-to-non-controlling-interests-ifrs-of :initform 0.0)
   (comparative-period-end-date-dei :accessor comparative-period-end-date-dei-of :initform nil)
   (current-assets-ifrs :accessor current-assets-ifrs-of :initform 0.0)
   (other-non-current-liabilities-ncl-ifrs :accessor other-non-current-liabilities-ncl-ifrs-of :initform 0.0)
   (other-income-ifrs :accessor other-income-ifrs-of :initform 0.0)
   (treasury-shares-ifrs :accessor treasury-shares-ifrs-of :initform 0.0)))

(defclass financial-statement-data (jquants-object)
  ((disclosed-date :accessor disclosed-date-of :initform 0)
   (disclosed-time :accessor disclosed-time-of :initform 0)
   (local-code :accessor local-code-of :initform nil)
   (disclosure-number :accessor disclosure-number-of :initform nil)
   (type-of-document :accessor type-of-document-of :initform nil)
   (financial-statement :accessor financial-statement-of :initform nil)
   (financial-statement-raw :accessor financial-statement-raw-of :initform nil)))

(defmethod handle-slot-value :after ((obj financial-statement-data) slot-name new-value)
  (when (eq slot-name 'financial-statement)
    (setf (financial-statement-raw-of obj) (financial-statement-of obj))
    (let ((fs (make-jquants-instance-from-hash-table
               :class financial-statement-detail-data
               :hash-table (financial-statement-raw-of obj))))
      (mapcar (lambda (accessor)
                (setf (slot-value fs accessor)
                      (%convert-string-to-epoch-time (slot-value fs accessor))))
              (list 'previous-fiscal-year-start-date-dei
                    'previous-fiscal-year-end-date-dei
                    'current-period-end-date-dei
                    'current-fiscal-year-start-date-dei
                    'current-fiscal-year-end-date-dei
                    'comparative-period-end-date-dei))
      (mapcar (lambda (accessor)
                (let ((flag (slot-value fs accessor)))
                  (setf (slot-value fs accessor)
                      (cond ((string= flag "true")
                             t)
                            ((string= flag "false")
                             nil)
                            (t
                             flag)))))
              (list 'whether-consolidated-financial-statements-are-prepared-dei
                    'xbrl-amendment-flag-dei
                    'amendment-flag-dei
                    'report-amendment-flag-dei))
      (setf (financial-statement-of obj) fs))))
