(in-package :cl-jquants-api)

(defclass financial-data (jquants-object)
  ((disclosed-date :accessor disclosed-date-of :initform 0)
   (disclosed-time :accessor disclosed-time-of :initform 0)
   (local-code :accessor local-code-of :initform nil)
   (disclosure-number :accessor disclosure-number-of :initform nil)
   (type-of-document :accessor type-of-document-of :initform nil)
   (type-of-current-period :accessor type-of-current-period-of :initform nil)
   (current-period-start-date :accessor current-period-start-date-of :initform 0)
   (current-period-end-date :accessor current-period-end-date-of :initform 0)
   (current-fiscal-year-start-date :accessor current-fiscal-year-start-date-of :initform 0)
   (current-fiscal-year-end-date :accessor current-fiscal-year-end-date-of :initform 0)
   (next-fiscal-year-start-date :accessor next-fiscal-year-start-date-of :initform 0)
   (next-fiscal-year-end-date :accessor next-fiscal-year-end-date-of :initform 0)
   (net-sales :accessor net-sales-of :initform 0.0)
   (operating-profit :accessor operating-profit-of :initform 0.0)
   (ordinary-profit :accessor ordinary-profit-of :initform 0.0)
   (profit :accessor profit-of :initform 0.0)
   (earnings-per-share :accessor earnings-per-share-of :initform 0.0)
   (diluted-earnings-per-share :accessor diluted-earnings-per-share-of :initform 0.0)
   (total-assets :accessor total-assets-of :initform 0.0)
   (equity :accessor equity-of :initform 0.0)
   (equity-to-asset-ratio :accessor equity-to-asset-ratio-of :initform 0.0)
   (book-value-per-share :accessor book-value-per-share-of :initform 0.0)
   (cash-flows-from-operating-activities :accessor cash-flows-from-operating-activities-of :initform 0.0)
   (cash-flows-from-investing-activities :accessor cash-flows-from-investing-activities-of :initform 0.0)
   (cash-flows-from-financing-activities :accessor cash-flows-from-financing-activities-of :initform 0.0)
   (cash-and-equivalents :accessor cash-and-equivalents-of :initform 0.0)
   (result-dividend-per-share1st-quarter :accessor result-dividend-per-share1st-quarter-of :initform 0.0)
   (result-dividend-per-share2nd-quarter :accessor result-dividend-per-share2nd-quarter-of :initform 0.0)
   (result-dividend-per-share3rd-quarter :accessor result-dividend-per-share3rd-quarter-of :initform 0.0)
   (result-dividend-per-share-fiscal-year-end :accessor result-dividend-per-share-fiscal-year-end-of :initform 0.0)
   (result-dividend-per-share-annual :accessor result-dividend-per-share-annual-of :initform 0.0)
   (distributions-per-unit-reit :accessor distributions-per-unit-reit-of :initform 0.0)
   (result-total-dividend-paid-annual :accessor result-total-dividend-paid-annual-of :initform 0.0)
   (result-payout-ratio-annual :accessor result-payout-ratio-annual-of :initform 0.0)
   (forecast-dividend-per-share1st-quarter :accessor forecast-dividend-per-share1st-quarter-of :initform 0.0)
   (forecast-dividend-per-share2nd-quarter :accessor forecast-dividend-per-share2nd-quarter-of :initform 0.0)
   (forecast-dividend-per-share3rd-quarter :accessor forecast-dividend-per-share3rd-quarter-of :initform 0.0)
   (forecast-dividend-per-share-fiscal-year-end :accessor forecast-dividend-per-share-fiscal-year-end-of :initform 0.0)
   (forecast-dividend-per-share-annual :accessor forecast-dividend-per-share-annual-of :initform 0.0)
   (forecast-distributions-per-unit-reit :accessor forecast-distributions-per-unit-reit-of :initform 0.0)
   (forecast-total-dividend-paid-annual :accessor forecast-total-dividend-paid-annual-of :initform 0.0)
   (forecast-payout-ratio-annual :accessor forecast-payout-ratio-annual-of :initform 0.0)
   (next-year-forecast-dividend-per-share1st-quarter :accessor next-year-forecast-dividend-per-share1st-quarter-of :initform 0.0)
   (next-year-forecast-dividend-per-share2nd-quarter :accessor next-year-forecast-dividend-per-share2nd-quarter-of :initform 0.0)
   (next-year-forecast-dividend-per-share3rd-quarter :accessor next-year-forecast-dividend-per-share3rd-quarter-of :initform 0.0)
   (next-year-forecast-dividend-per-share-fiscal-year-end :accessor next-year-forecast-dividend-per-share-fiscal-year-end-of :initform 0.0)
   (next-year-forecast-dividend-per-share-annual :accessor next-year-forecast-dividend-per-share-annual-of :initform 0.0)
   (next-year-forecast-distributions-per-unit-reit :accessor next-year-forecast-distributions-per-unit-reit-of :initform 0.0)
   (next-year-forecast-payout-ratio-annual :accessor next-year-forecast-payout-ratio-annual-of :initform 0.0)
   (forecast-net-sales2nd-quarter :accessor forecast-net-sales2nd-quarter-of :initform 0.0)
   (forecast-operating-profit2nd-quarter :accessor forecast-operating-profit2nd-quarter-of :initform 0.0)
   (forecast-ordinary-profit2nd-quarter :accessor forecast-ordinary-profit2nd-quarter-of :initform 0.0)
   (forecast-profit2nd-quarter :accessor forecast-profit2nd-quarter-of :initform 0.0)
   (forecast-earnings-per-share2nd-quarter :accessor forecast-earnings-per-share2nd-quarter-of :initform 0.0)
   (next-year-forecast-net-sales2nd-quarter :accessor next-year-forecast-net-sales2nd-quarter-of :initform 0.0)
   (next-year-forecast-operating-profit2nd-quarter :accessor next-year-forecast-operating-profit2nd-quarter-of :initform 0.0)
   (next-year-forecast-ordinary-profit2nd-quarter :accessor next-year-forecast-ordinary-profit2nd-quarter-of :initform 0.0)
   (next-year-forecast-profit2nd-quarter :accessor next-year-forecast-profit2nd-quarter-of :initform 0.0)
   (next-year-forecast-earnings-per-share2nd-quarter :accessor next-year-forecast-earnings-per-share2nd-quarter-of :initform 0.0)
   (forecast-net-sales :accessor forecast-net-sales-of :initform 0.0)
   (forecast-operating-profit :accessor forecast-operating-profit-of :initform 0.0)
   (forecast-ordinary-profit :accessor forecast-ordinary-profit-of :initform 0.0)
   (forecast-profit :accessor forecast-profit-of :initform 0.0)
   (forecast-earnings-per-share :accessor forecast-earnings-per-share-of :initform 0.0)
   (next-year-forecast-net-sales :accessor next-year-forecast-net-sales-of :initform 0.0)
   (next-year-forecast-operating-profit :accessor next-year-forecast-operating-profit-of :initform 0.0)
   (next-year-forecast-ordinary-profit :accessor next-year-forecast-ordinary-profit-of :initform 0.0)
   (next-year-forecast-profit :accessor next-year-forecast-profit-of :initform 0.0)
   (next-year-forecast-earnings-per-share :accessor next-year-forecast-earnings-per-share-of :initform 0.0)
   (material-changes-in-subsidiaries :accessor material-changes-in-subsidiaries-of :initform nil)
   (significant-changes-in-the-scope-of-consolidation :accessor significant-changes-in-the-scope-of-consolidation-of :initform nil)
   (changes-based-on-revisions-of-accounting-standard :accessor changes-based-on-revisions-of-accounting-standard-of :initform nil)
   (changes-other-than-ones-based-on-revisions-of-accounting-standard :accessor changes-other-than-ones-based-on-revisions-of-accounting-standard-of :initform nil)
   (changes-in-accounting-estimates :accessor changes-in-accounting-estimates-of :initform nil)
   (retrospective-restatement :accessor retrospective-restatement-of :initform nil)
   (number-of-issued-and-outstanding-shares-at-the-end-of-fiscal-year-including-treasury-stock :accessor number-of-issued-and-outstanding-shares-at-the-end-of-fiscal-year-including-treasury-stock-of :initform 0.0)
   (number-of-treasury-stock-at-the-end-of-fiscal-year :accessor number-of-treasury-stock-at-the-end-of-fiscal-year-of :initform 0.0)
   (average-number-of-shares :accessor average-number-of-shares-of :initform 0.0)
   (non-consolidated-net-sales :accessor non-consolidated-net-sales-of :initform 0.0)
   (non-consolidated-operating-profit :accessor non-consolidated-operating-profit-of :initform 0.0)
   (non-consolidated-ordinary-profit :accessor non-consolidated-ordinary-profit-of :initform 0.0)
   (non-consolidated-profit :accessor non-consolidated-profit-of :initform 0.0)
   (non-consolidated-earnings-per-share :accessor non-consolidated-earnings-per-share-of :initform 0.0)
   (non-consolidated-total-assets :accessor non-consolidated-total-assets-of :initform 0.0)
   (non-consolidated-equity :accessor non-consolidated-equity-of :initform 0.0)
   (non-consolidated-equity-to-asset-ratio :accessor non-consolidated-equity-to-asset-ratio-of :initform 0.0)
   (non-consolidated-book-value-per-share :accessor non-consolidated-book-value-per-share-of :initform 0.0)
   (forecast-non-consolidated-net-sales2nd-quarter :accessor forecast-non-consolidated-net-sales2nd-quarter-of :initform 0.0)
   (forecast-non-consolidated-operating-profit2nd-quarter :accessor forecast-non-consolidated-operating-profit2nd-quarter-of :initform 0.0)
   (forecast-non-consolidated-ordinary-profit2nd-quarter :accessor forecast-non-consolidated-ordinary-profit2nd-quarter-of :initform 0.0)
   (forecast-non-consolidated-profit2nd-quarter :accessor forecast-non-consolidated-profit2nd-quarter-of :initform 0.0)
   (forecast-non-consolidated-earnings-per-share2nd-quarter :accessor forecast-non-consolidated-earnings-per-share2nd-quarter-of :initform 0.0)
   (next-year-forecast-non-consolidated-net-sales2nd-quarter :accessor next-year-forecast-non-consolidated-net-sales2nd-quarter-of :initform 0.0)
   (next-year-forecast-non-consolidated-operating-profit2nd-quarter :accessor next-year-forecast-non-consolidated-operating-profit2nd-quarter-of :initform 0.0)
   (next-year-forecast-non-consolidated-ordinary-profit2nd-quarter :accessor next-year-forecast-non-consolidated-ordinary-profit2nd-quarter-of :initform 0.0)
   (next-year-forecast-non-consolidated-profit2nd-quarter :accessor next-year-forecast-non-consolidated-profit2nd-quarter-of :initform 0.0)
   (next-year-forecast-non-consolidated-earnings-per-share2nd-quarter :accessor next-year-forecast-non-consolidated-earnings-per-share2nd-quarter-of :initform 0.0)
   (forecast-non-consolidated-net-sales :accessor forecast-non-consolidated-net-sales-of :initform 0.0)
   (forecast-non-consolidated-operating-profit :accessor forecast-non-consolidated-operating-profit-of :initform 0.0)
   (forecast-non-consolidated-ordinary-profit :accessor forecast-non-consolidated-ordinary-profit-of :initform 0.0)
   (forecast-non-consolidated-profit :accessor forecast-non-consolidated-profit-of :initform 0.0)
   (forecast-non-consolidated-earnings-per-share :accessor forecast-non-consolidated-earnings-per-share-of :initform 0.0)
   (next-year-forecast-non-consolidated-net-sales :accessor next-year-forecast-non-consolidated-net-sales-of :initform 0.0)
   (next-year-forecast-non-consolidated-operating-profit :accessor next-year-forecast-non-consolidated-operating-profit-of :initform 0.0)
   (next-year-forecast-non-consolidated-ordinary-profit :accessor next-year-forecast-non-consolidated-ordinary-profit-of :initform 0.0)
   (next-year-forecast-non-consolidated-profit :accessor next-year-forecast-non-consolidated-profit-of :initform 0.0)
   (next-year-forecast-non-consolidated-earnings-per-share :accessor next-year-forecast-non-consolidated-earnings-per-share-of :initform 0.0)))

(defmethod complete-object-update :after ((obj financial-data))
  (if (string= (material-changes-in-subsidiaries-of obj) "true")
      (setf (material-changes-in-subsidiaries-of obj) t)
      (setf (material-changes-in-subsidiaries-of obj) nil))
  (if (string= (significant-changes-in-the-scope-of-consolidation-of obj) "true")
      (setf (significant-changes-in-the-scope-of-consolidation-of obj) t)
      (setf (significant-changes-in-the-scope-of-consolidation-of obj) nil))
  (if (string= (changes-based-on-revisions-of-accounting-standard-of obj) "true")
      (setf (changes-based-on-revisions-of-accounting-standard-of obj) t)
      (setf (changes-based-on-revisions-of-accounting-standard-of obj) nil))
  (if (string= (changes-other-than-ones-based-on-revisions-of-accounting-standard-of obj) "true")
      (setf (changes-other-than-ones-based-on-revisions-of-accounting-standard-of obj) t)
      (setf (changes-other-than-ones-based-on-revisions-of-accounting-standard-of obj) nil))
  (if (string= (changes-in-accounting-estimates-of obj) "true")
      (setf (changes-in-accounting-estimates-of obj) t)
      (setf (changes-in-accounting-estimates-of obj) nil))
  (if (string= (retrospective-restatement-of obj) "true")
      (setf (retrospective-restatement-of obj) t)
      (setf (retrospective-restatement-of obj) nil)))
