(in-package :cl-jquants-api)

(defclass options-data (jquants-object)
  ((code :accessor code-of :initform nil)
   (derivatives-product-category :accessor derivatives-product-category-of :initform nil)
   (underlying-sso :accessor underlying-sso-of :initform nil)
   (date :accessor date-of :initform 0)
   (whole-day-open :accessor whole-day-open-of :initform 0.0)
   (whole-day-high :accessor whole-day-high-of :initform 0.0)
   (whole-day-low :accessor whole-day-low-of :initform 0.0)
   (whole-day-close :accessor whole-day-close-of :initform 0.0)
   (morning-session-open :accessor morning-session-open-of :initform 0.0)
   (morning-session-high :accessor morning-session-high-of :initform 0.0)
   (morning-session-low :accessor morning-session-low-of :initform 0.0)
   (morning-session-close :accessor morning-session-close-of :initform 0.0)
   (night-session-open :accessor night-session-open-of :initform 0.0)
   (night-session-high :accessor night-session-high-of :initform 0.0)
   (night-session-low :accessor night-session-low-of :initform 0.0)
   (night-session-close :accessor night-session-close-of :initform 0.0)
   (day-session-open :accessor day-session-open-of :initform 0.0)
   (day-session-high :accessor day-session-high-of :initform 0.0)
   (day-session-low :accessor day-session-low-of :initform 0.0)
   (day-session-close :accessor day-session-close-of :initform 0.0)
   (volume :accessor volume-of :initform 0.0)
   (open-interest :accessor open-interest-of :initform 0.0)
   (turnover-value :accessor turnover-value-of :initform 0.0)
   (contract-month :accessor contract-month-of :initform nil)
   (strike-price :accessor strike-price-of :initform 0.0)
   (volume-only-auction :accessor volume-only-auction-of :initform 0.0)
   (emergency-margin-trigger-division :accessor emergency-margin-trigger-division-of :initform nil)
   (put-call-division :accessor put-call-division-of :initform nil)
   (last-trading-day :accessor last-trading-day-of :initform nil)
   (special-quotation-day :accessor special-quotation-day-of :initform nil)
   (settlement-price :accessor settlement-price-of :initform 0.0)
   (theoretical-price :accessor theoretical-price-of :initform 0.0)
   (base-volatility :accessor base-volatility-of :initform 0.0)
   (underlying-price :accessor underlying-price-of :initform 0.0)
   (implied-volatility :accessor implied-volatility-of :initform 0.0)
   (interest-rate :accessor interest-rate-of :initform 0.0)
   (central-contract-month-flag :accessor central-contract-month-flag-of :initform nil)))

(defmethod complete-object-update ((obj options-data))
  (setf (put-call-division-of obj)
        (if (string= (put-call-division-of obj) "1")
             :put
             :call))
  (setf (central-contract-month-flag-of obj)
        (if (string= (central-contract-month-flag-of obj) "1")
            :central-contract-month
            :others))
  (when (stringp (morning-session-open-of obj))
    (setf (morning-session-open-of obj) nil))
  (when (stringp (morning-session-high-of obj))
    (setf (morning-session-high-of obj) nil))
  (when (stringp (morning-session-low-of obj))
    (setf (morning-session-low-of obj) nil))
  (when (stringp (morning-session-close-of obj))
    (setf (morning-session-close-of obj) nil))
  (when (stringp (night-session-open-of obj))
    (setf (night-session-open-of obj) nil))
  (when (stringp (night-session-high-of obj))
    (setf (night-session-high-of obj) nil))
  (when (stringp (night-session-low-of obj))
    (setf (night-session-low-of obj) nil))
  (when (stringp (night-session-close-of obj))
    (setf (night-session-close-of obj) nil)))
